name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Restore
      run: npm ci
    - name: Build
      run: npm run build
    - name: Format
      run: npm run fmt
